# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.6.0
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: mubahussen2014@gmail.com
author_name: mubarek
contract_name: calculator
deployment_language: python
ide_vscode: true
preset_name: starter
project_name: algorand
use_python_black: true
use_python_pytest: true

